site_name: Lunr.py

nav:
  - Home: index.md
  - Searching: usage.md
  - Building indices: indices.md
  - Languages: languages.md
  - Interoperability with Lunr.js: lunrjs-interop.md

theme: readthedocs

markdown_extensions:
  - admonition
